🏹 Upgrade Elixir version
mbta/arrow pull request #1024
Opened 2024-10-24 17:22 UTC by Whoops

#### Summary of changes
**Asana Ticket:** [🏹 Upgrade Elixir version](https://app.asana.com/0/1204137169527258/1208367835950806/f)

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes.

2024-10-24 17:30 UTC, Whoops commented on config/runtime.exs
> -      included_environments: [sentry_env]
https://hexdocs.pm/sentry/upgrade-10-x.html#stop-using-included_environments

2024-10-24 17:34 UTC, Whoops commented on mix.exs
> +      {:ja_serializer, "~> 0.18.0"},
Our version of ja_serializer has diverged from upstream, but also not been touched in 3 years. Best I could tell Arrow does not appear to rely on any MBTA specific behaviors.

2024-10-24 18:01 UTC, Whoops commented on lib/arrow_web/controllers/shape_controller.ex
> -      error ->
Dialyzer flags this clause as unreachable, and I agree. `parse_kml_from_file` and `shapes_from_kml` will always return `{:ok, _}` or `{:error, _}`, and `changeset` will always return a changeset, so will always match.

2024-10-24 18:03 UTC, Whoops commented on mix.exs
> +        plt_add_deps: :app_tree,
https://hexdocs.pm/dialyxir/changelog.html#changed-3

2024-10-24 21:16 UTC, Whoops commented on mix.exs
> -        ignore_warnings: ".dialyzer.ignore-warnings"
Dialyzer complained about `could not read file stats ".dialyzer_ignore.exs": no such file or directory` as long as this was present. I didn't figure out why, but we also aren't ignoring warnings (.dialyzer.ignore-warnings is blank) so I removed it.

2024-10-24 21:19 UTC, Whoops commented on Dockerfile
> +RUN mix sentry.package_source_code
https://hexdocs.pm/sentry/upgrade-10-x.html#what-do-i-have-to-do

2024-10-28 16:49 UTC, meagharty requested changes

2024-10-28 16:49 UTC, meagharty commented on test/arrow_web/controllers/stop_controller_test.exs
> +      assert conn.assigns.flash["errors"] ==
```suggestion
      assert Phoenix.Flash.get(conn.assigns.flash, :errors) ==
```

2024-10-28 16:49 UTC, meagharty commented on mix.exs
> +      {:ja_serializer, "~> 0.18.0"},
I'm in support of this change since our version hasn't been maintained.

Was this upgrade of `ja_serializer` required as part of upgrading the elixir version though?

Can we split this change into it's own separate PR? If we notice any unexpected changes (like with the gtfs_creator build when parsing API results, performance issues with endpoints, whatever), it'd be easier to isolate that way.

2024-10-28 18:15 UTC, Whoops commented on mix.exs
> +      {:ja_serializer, "~> 0.18.0"},
Looks like it can be. Some of these depredations were forced since we compile with `--warnings-as-errors` in the test phase, but while keeping `ja_serializer` generates warnings during tests, it seems to compile happily. I've split it into #1026

2024-10-28 21:22 UTC, meagharty approved these changes
🎉

2024-10-28 21:22 UTC, meagharty commented on lib/arrow/disruption_revision.ex
> +  defp date_range(start_date, end_date) do
I think the code below is correct but what you meant in this comment was `start_date > end_date` for step of -1 (so it enumerates backwards in time from start_date to end_date)

2024-10-29 17:45 UTC, merged