feat(shapes): switch map to MBTA tileset
mbta/arrow pull request #1045
Opened 2024-12-04 19:41 UTC by rudiejd

#### Summary of changes
**Asana Ticket:** [🏹 Implement Skate Tileset](https://app.asana.com/0/inbox/1208877353871379/1208652433539040/1208898327310338)

Change tileset from default OSM tileset to MBTA tileset used on Skate.
![image](https://github.com/user-attachments/assets/06bfb47f-cf09-44b5-996d-a81b18955134)

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes.

2024-12-04 19:47 UTC, rudiejd commented on docker-compose.yml
> +    environment:
I can remove if we would rather leave this out of version control, but I find a compose file useful for getting postgres up and running

2024-12-04 19:52 UTC, rudiejd commented on assets/src/components/ShapeViewMap.tsx
> +        attribution='&copy; <a href="https://www.mass.gov/info-details/massgis-data-2021-aerial-imagery">MassGIS 2021</a>'
do we want this to be configurable? I couldn't grok any other examples of configurable values in the React part of the app, this was static before, so I just left it hard-coded. But I don't think that's ideal, since the s3 bucket could change

2024-12-06 20:41 UTC, meagharty requested changes

2024-12-06 20:41 UTC, meagharty commented on assets/src/components/ShapeViewMap.tsx
> +        attribution='&copy; <a href="https://www.mass.gov/info-details/massgis-data-2021-aerial-imagery">MassGIS 2021</a>'
I doubt we'll change the s3 bucket or tileset anytime soon.

Maybe if we hit another instance of changing this or we want to add options within the map view to change the tileset? It doesn't seem worth it to me to plumb that into this part of the app atm but it's up to you.

To your point, afaik we don't have any app-level [config/...](https://github.com/mbta/arrow/tree/master/config) plumbing yet for React (like skate does w/ [appData.ts](https://github.com/mbta/skate/blob/8d6a841d98813185982edd52b8ce5b583503c55c/assets/src/appData.ts) and this server-side [`<div id="app" />`](https://github.com/mbta/skate/blob/8d6a841d98813185982edd52b8ce5b583503c55c/lib/skate_web/controllers/page_html/index.html.heex#L8))

2024-12-06 20:41 UTC, meagharty commented on docker-compose.yml
> +    environment:
this is nice, thank you! makes sense to add it to version control to share with others

2024-12-06 20:41 UTC, meagharty commented on docker-compose.yml
> +    image: postgres:14.1-alpine
why `14.1`?

our prod database is running [15.4](https://github.com/mbta/devops/blob/d73667663604d51c5b4d606de59a098f79202025/terraform/aws-tid-main-prod/arrow.tf#L19) so we should use a version of 15

It looks like the README is out of date (says `postgresql@11`). Do you mind updating the README with `15` and adding this docker-compose file as an option for setting up PostgreSQL?

2024-12-06 20:41 UTC, meagharty commented on docker-compose.yml
> +    driver: local
nit: `local` seems to be the default for `driver`, do you specify it here for any reason in particular?

2024-12-06 21:18 UTC, rudiejd commented on docker-compose.yml
> +    image: postgres:14.1-alpine
i think i just copied this from another project 😅 

i made those changes!

2024-12-06 21:20 UTC, rudiejd commented on docker-compose.yml
> +    driver: local
yep, I think I just tend to forget that you can specify the volumes as simply

```
volume:
    foo:
```
without saying a driver, because it feels a little weird. but i think that is indeed the modern way to do it. I changed that

2024-12-06 21:22 UTC, rudiejd commented on assets/src/components/ShapeViewMap.tsx
> +        attribution='&copy; <a href="https://www.mass.gov/info-details/massgis-data-2021-aerial-imagery">MassGIS 2021</a>'
I think we can do that as part of https://app.asana.com/0/1203810889612417/1208652433539046/f

2024-12-06 21:31 UTC, meagharty approved these changes

2024-12-06 21:39 UTC, merged