feat(shuttle-stops): shuttle stops map view draft
mbta/arrow pull request #1054
Opened 2024-12-12 22:11 UTC by rudiejd

#### Summary of changes
**Asana Ticket:** [TICKET_NAME](TICKET_LINK)

[Please include a brief description of what was changed]

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes.

2024-12-13 22:28 UTC, rudiejd commented
I'm not really sure how to add automated tests for a mostly visual/javascript feature like this, save for browser-based tests. Happy to add them if folks think it's important for this though

2024-12-13 22:32 UTC, rudiejd commented on assets/src/components/stops/types.tsx
> +  stop_lon: number
I chose to make these different frontend types even though they have exactly the same data because I figured we might want different information from them in the future, and the schema for these types on the backend is not exactly the same

2024-12-16 14:39 UTC, cmaddox5 commented on assets/src/components/stops/StopViewMap.tsx
> +            {existingShuttleStops?.map(
nit: Shouldn't need to worry about `existingShuttleStops` being `null`-ish here since there is a check above. Same for line 95 below.

2024-12-16 14:39 UTC, cmaddox5 commented on assets/src/components/stops/StopViewMap.tsx
> +        </LayersControl.Overlay>
To reduce duplication, might be useful to extract this `LayersControl.Overlay` group into its own component that takes in the data it needs in `props`. Would make future changes to them a little easier.

2024-12-16 14:39 UTC, cmaddox5 commented on assets/src/components/stops/StopViewMap.tsx
> +const genIcon = (color: string) => {
It looks like this function will eventually return the same thing as the function in #1047. Makes sense cause they both represent a map marker. Not sure the best way to coordinate this, but should we think about exporting the function and using it in both places?

2024-12-16 14:39 UTC, cmaddox5 commented on assets/src/components/stops/types.tsx
> +  stop_lon: number
I think this is fine considering the property names are different.

2024-12-16 14:44 UTC, rudiejd commented on assets/src/components/stops/StopViewMap.tsx
> +const genIcon = (color: string) => {
@Whoops do you mind if I move this into a common helper function? not sure whose PR will be merged first 😅

2024-12-16 20:30 UTC, Whoops commented on assets/src/components/stops/StopViewMap.tsx
> +const genIcon = (color: string) => {
I'm all for it! I expect there's a lot of common functionality that could be extracted in a factor, if not making a map component that's used across all pages. But that's probably another ticket :-)

2024-12-16 20:37 UTC, rudiejd commented on assets/src/components/stops/StopViewMap.tsx
> +        setLayersEnabled({ ...layersEnabled, stop: false })
This is kind of janky. The idea here was to track the state of overlay-layers and change the bounds of the map based on all currently enabled and valid stops

2024-12-16 20:44 UTC, Whoops commented on assets/src/components/stops/StopViewMap.tsx
> +        setLayersEnabled({ ...layersEnabled, stop: false })
Responding to this comment having not read the code; my apologies if this is something already factored in...

I don't think you should consider anything except the currently selected stop when setting the bounds. Otherwise, when bus stops are enabled, you'll essentially end up looking at the greater Boston area when the intent of the feature is to give you an idea of what other stops are near the one you are about to create or are looking at.

2024-12-16 20:54 UTC, rudiejd commented on assets/src/components/stops/StopViewMap.tsx
> +        setLayersEnabled({ ...layersEnabled, stop: false })
gotcha, that will make this way easier then 😅  i will make that change

2024-12-16 21:07 UTC, rudiejd commented on assets/src/components/stops/StopViewMap.tsx
> +        </LayersControl.Overlay>
upon further inspection, I made the zoom/bound-setting code way overly complicated, and after refactoring I didn't need the names of each overlay layer. so I pulled this out

2024-12-16 21:56 UTC, cmaddox5 commented on assets/src/components/stops/StopViewMap.tsx
> +    const bounds = getMapBounds(
I'm noticing a pretty big pause on dev when checking `Existing Bus Stop`. I think it's because the map is rendering markers outside the visible bounds. If you zoom out a ton, the page will eventually just stop working. Is it possible to prevent rendering outside the visible bounds in `react-leaflet`?

2024-12-17 21:50 UTC, rudiejd commented on assets/src/components/stops/StopLayerControl.tsx
> +              .filter(
Discussion about this change: https://mbta.slack.com/archives/C07639BHFKR/p1734467848132149

I opted to only render stops within 1 radius of the stop you are creating / editing. This needs to be done in the client side code because in the case of a new stop, the latitude and longitude aren't propogated to the backend until after the user saves the stop, so they wouldn't be able to see the new stop on a map while editing it

2024-12-18 16:07 UTC, cmaddox5 approved these changes
Big performance improvement with the new filter logic. Very cool. Have a couple more small comments/suggestions.

2024-12-18 16:37 UTC, rudiejd commented on config/runtime.exs
> +    check_origin: [
yeah, I can do that. I just had to cherry pick that commit for the map to display on dev

2024-12-18 18:19 UTC, cmaddox5 requested changes
Sorry to retract approval, but I think we should actually reconsider how we load GTFS stops on page load. Going and getting all stops will be very taxing considering how many we have. Now that I look at dev again, you can actually see the effect of the performance issue on the map. It takes a second or more to load after the rest of the page.

2024-12-19 15:47 UTC, cmaddox5 commented on assets/src/components/stops/StopLayerControl.tsx
> +      {existingShuttleStops && existingShuttleStops.length > 0 && (
```suggestion
      {existingShuttleStops?.length > 0 && (
```

2024-12-19 15:47 UTC, cmaddox5 commented on assets/src/components/stops/StopLayerControl.tsx
> +              .filter(
Now that the server does this, shouldn't need to do it here.

2024-12-19 15:47 UTC, cmaddox5 commented on assets/src/components/util/maps.tsx
> +const haversineDistanceMiles = (
Shouldn't need this anymore.

2024-12-19 15:47 UTC, cmaddox5 commented on assets/tests/components/StopViewMap.test.tsx
> +    )
I think the assertion above this one is good to keep, but now that the server does the distance work you don't need to test against it here.

2024-12-19 15:47 UTC, cmaddox5 commented on config/runtime.exs
> +    check_origin: [
Just a reminder to remove this commit before merging.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow/gtfs/stop.ex
> +  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
If I'm reading this right, you should be able to combine both of these functions. The ID comparison would be harmless if it is `nil` because no ID will equal `nil` anyway and would be `true` for all rows.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow/gtfs/stop.ex
> +          s.lat <= ^lat + @latitude_degrees_per_mile and
Should we consider a new index for lat and long columns now? I don't think this table has any atm.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow/stops.ex
> +  def get_stops_within_mile(stop_id, {lat, lon}) do
Can combine these, too.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow/stops.ex
> +          s.stop_lat <= ^lat + @latitude_degrees_per_mile and
Same question on indexes for this table.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow_web/live/stop_live/stop_live.ex
> +      |> assign(:existing_gtfs_stops, nil)
suggestion: Default these to `[]` and you can remove a lot of `null` checks in the client code.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow_web/live/stop_live/stop_live.ex
> +  end
These appear to be unused.

2024-12-19 15:47 UTC, cmaddox5 commented on lib/arrow_web/live/stop_live/stop_live.ex
> +      end
Could make this a bit more concise:
```suggestion
    {existing_stops, existing_gtfs_stops} =
      case stop_params do
        %{"stop_lat" => lat, "stop_lon" => lon, "id" => stop_id}
        when not is_nil(lat) and not is_nil(lon) ->
          lat_float = String.to_float(lat)
          lon_float = String.to_float(lon)

          {Stops.get_stops_within_mile(stop_id, {lat_float, lon_float}),
           GtfsStop.get_stops_within_mile(stop_id, {lat_float, lon_float})}

        _ ->
          {nil, nil}
      end
```

2024-12-19 15:47 UTC, cmaddox5 commented on test/arrow/stops_test.exs
> +    test "get_stops_within_mile/2 returns stops roughly within one mile of a stop" do
Can a similar test be added for GTFS Stops? Either that or find a way to let them share the same function and test the shared version.

2024-12-19 15:50 UTC, rudiejd commented on assets/src/components/stops/StopLayerControl.tsx
> +              .filter(
The server actually does a more approximate version of this. if, for some reason, we wanted to do an exact 1 mile radius, we could keep it this way. But I can remove this for now

2024-12-19 15:52 UTC, rudiejd commented on test/arrow/stops_test.exs
> +    test "get_stops_within_mile/2 returns stops roughly within one mile of a stop" do
There's a test for gtfs_stops here: https://github.com/mbta/arrow/blob/afe44459b0434ea8a413ff7ffbfe46617c651ba9/test/arrow/gtfs/stop_test.exs#L6

2024-12-19 15:56 UTC, cmaddox5 commented on test/arrow/stops_test.exs
> +    test "get_stops_within_mile/2 returns stops roughly within one mile of a stop" do
That gives a 404. Does it still need to be committed/pushed?

2024-12-19 15:56 UTC, rudiejd commented on lib/arrow_web/live/stop_live/stop_live.ex
> +  end
oops, forgot to remove those 😅

2024-12-19 16:00 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
I actually was getting a runtime exception when I compared with `nil` in the Ecto code: https://github.com/elixir-ecto/ecto/blob/e644970b6b22369f2acec58ed5c598685488eee8/lib/ecto/query/builder/filter.ex#L191

I could handle this with branching logic rather than pattern matching on the function signature if you prefer that

2024-12-19 16:02 UTC, rudiejd commented on test/arrow/stops_test.exs
> +    test "get_stops_within_mile/2 returns stops roughly within one mile of a stop" do
oops, I forgot to `git add` that new file 😭 should be good now

2024-12-19 16:14 UTC, cmaddox5 commented on lib/arrow/gtfs/stop.ex
> +  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
Hmm TIL! Haven't worked with Ecto a ton yet.

But the branching logic might be better just for the sake of keeping all the math in one place.

2024-12-19 16:19 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +          s.lat <= ^lat + @latitude_degrees_per_mile and
query plan before index
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on gtfs_stops  (cost=0.00..472.75 rows=2 width=279)
   Filter: ((lat >= '42.3774'::double precision) AND (lat <= '42.3784'::double precision) AND (lon >= '-71.1182'::double precision) AND (lon <= '-71.1082'::double precision) AND ((id)::text <> '1'::text))
(2 rows)
```

2024-12-19 16:29 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +          s.lat <= ^lat + @latitude_degrees_per_mile and
query plan after index
```
 Bitmap Heap Scan on gtfs_stops  (cost=4.98..12.48 rows=2 width=279)
   Recheck Cond: ((lat >= '42.3774'::double precision) AND (lat <= '42.3784'::double precision) AND (lon >= '-71.1182'::double precision) AND (lon <= '-71.1082'::double precision))
   Filter: ((id)::text <> '1'::text)
   ->  Bitmap Index Scan on gtfs_stops_lat_lon_vehicle_type_id_index  (cost=0.00..4.98 rows=2 width=0)
         Index Cond: ((lat >= '42.3774'::double precision) AND (lat <= '42.3784'::double precision) AND (lon >= '-71.1182'::double precision) AND (lon <= '-71.1082'::double precision))
```

reduces total cost from 472.75 to 12.48

2024-12-19 16:35 UTC, rudiejd commented on lib/arrow/stops.ex
> +  def get_stops_within_mile(stop_id, {lat, lon}) do
same problem as here: https://github.com/mbta/arrow/pull/1054#discussion_r1892591201

2024-12-19 16:53 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
credo marks this is a refactoring opportunity when I try to branch the query, hah
```elixir
  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
    query =
      if is_nil(arrow_stop_id) do
        from(s in Arrow.Gtfs.Stop,
          where:
            s.lat <= ^lat + @latitude_degrees_per_mile and
              s.lat >= ^lat - @latitude_degrees_per_mile and
              s.lon <= ^lon + @longitude_degrees_per_mile and
              s.lon >= ^lon - @latitude_degrees_per_mile and
              s.vehicle_type == :bus
        )
      else
        from(s in Arrow.Gtfs.Stop,
          where:
            s.id != ^arrow_stop_id and
              s.lat <= ^lat + @latitude_degrees_per_mile and
              s.lat >= ^lat - @latitude_degrees_per_mile and
              s.lon <= ^lon + @longitude_degrees_per_mile and
              s.lon >= ^lon - @latitude_degrees_per_mile
        )
      end

    query |> Repo.all()
  end
```

```
[F] → Function is too complex (cyclomatic complexity is 10, max is 9).
┃       lib/arrow/gtfs/stop.ex:103:7 #(Arrow.Gtfs.Stop.get_stops_within_mile)
```

I think the cyclomatic complexity calculation is incorrect for macros

2024-12-19 17:17 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +  def get_stops_within_mile(arrow_stop_id, {lat, lon}) do
I found a way to rewrite this using dynamic query expressions 👍

2024-12-19 18:58 UTC, cmaddox5 approved these changes
Looking good! Last things are pretty small. Thanks for bearing with me. Shouldn't need to see it on dev anymore so should be good to pull out the `Endpoint` change now.

2024-12-19 18:58 UTC, cmaddox5 commented on assets/src/components/stops/types.tsx
> +  stop_id?: string
I believe all of these are required fields so they shouldn't need to be nullable.

2024-12-19 18:58 UTC, cmaddox5 commented on assets/src/components/util/maps.tsx
> +    return undefined
nit: `null` feels like a more appropriate return here to me.

2024-12-19 18:58 UTC, cmaddox5 commented on assets/src/components/stops/types.tsx
> +  stop_id?: string
Or is this specifically for `/new`?

2024-12-19 18:58 UTC, cmaddox5 commented on lib/arrow/gtfs/stop.ex
> +    conditions =
When `arrow_stop_id` is `nil`, I believe `conditions` would then be set to `nil` and you would lose all the above conditions. You could solve it be doing something like:
```elixir
conditions = if is_nil(arrow_stop_id), do: conditions, else: dynamic([s], s.id != ^arrow_stop_id and ^conditions)
```

2024-12-19 18:58 UTC, cmaddox5 commented on lib/arrow/stops.ex
> +      if not is_nil(stop_id) do
Same concern as above.

2024-12-19 18:58 UTC, cmaddox5 commented on lib/arrow/gtfs/stop.ex
> +        s.lat <= ^lat + @latitude_degrees_per_mile and
I see `vehicle_type` was added to the index but am not seeing it in the query.

2024-12-19 19:04 UTC, rudiejd commented on assets/src/components/stops/types.tsx
> +  stop_id?: string
yep, this is for `/new`

2024-12-19 19:23 UTC, rudiejd commented on lib/arrow/gtfs/stop.ex
> +        s.lat <= ^lat + @latitude_degrees_per_mile and
oops, I think i wiped it out when switching to use dynamic ecto expressions. bringing that back

2024-12-19 19:54 UTC, merged