test: add integration tests for disruption creation
mbta/arrow pull request #734
Opened 2021-08-13 17:35 UTC by bklebe

#### Summary of changes
**Asana Ticket:** [Integration tests](https://app.asana.com/0/584764604969369/1200671066645720/f)

Adds integration tests with Wallaby for disruption creation, filtering in list view, and viewing via the calendar. Ensures the Ecto Sandbox is properly setup for testing.

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes.

2021-08-14 17:48 UTC, losvedir requested changes
This is awesome! Thanks for figuring out how to set this up. A few changes requested, since you're out this sprint, I think I'll try to see about pushing up a commit to address them.

2021-08-14 17:48 UTC, losvedir commented on test/integration/disruptions_test.exs
> +  feature "can view disruption on home page", %{session: session} do
Like the "view on calendar", I think this test should create the data in the test here with a factory. And then the form part can be its own feature.

2021-08-15 03:33 UTC, bklebe commented on mix.exs
> +    if "--compile-assets" in args do
Yes, in that event we should do it always.

2021-08-15 03:34 UTC, bklebe commented on test/integration/disruptions_test.exs
> +  feature "can view disruption on home page", %{session: session} do
I assumed it would just be simpler to do both in one test. What’s the advantage of splitting them up?

2021-08-15 03:34 UTC, bklebe commented on mix.exs
> +  defp elixirc_paths(:test), do: ["lib", "test/support", "test/integration"]
No, probably not.

2021-08-15 03:35 UTC, bklebe commented on lib/arrow_web/endpoint.ex
> +  if sandbox = Application.get_env(:arrow, :sandbox) do
Not sure, it will definitely be set at compile time in the file, but I assumed it would still read at runtime.

2021-08-15 03:38 UTC, bklebe commented on config/test.exs
> +config :arrow, sandbox: Ecto.Adapters.SQL.Sandbox
For your first comment, yes, good call. For the second, I don’t think I added the line setting the test env? But no, I don’t think we’ll ever use a different sandbox, or use the sandbox outside of the test environment.

2021-08-24 15:38 UTC, digitalcora commented on README.md
> +- `brew install --cask chromedriver`
Specifying `--cask` shouldn't be needed anymore: `brew install chromedriver` works.

2021-08-31 20:07 UTC, losvedir commented on config/test.exs
> +config :arrow, sandbox: Ecto.Adapters.SQL.Sandbox
For the second comment: right, I mean `env: :test` is already in there, and I'm suggesting we can just use that instead of adding something new.

2021-08-31 20:11 UTC, losvedir commented on lib/arrow_web/endpoint.ex
> +  if sandbox = Application.get_env(:arrow, :sandbox) do
I believe it should be `compile_env`. Since this is top-level code within the module, the configuration value will be read when the module is compiled, and so the presence (or not) of the `plug` will be decided then, and can't be changed during runtim.

`Application.compile_env/2` and `Application.get_env/2` are basically the same, I think, except that the former will help Elixir realize the dependency between this file and the configuration, and so know to recompile it if we change that.

2021-08-31 20:12 UTC, losvedir commented on mix.exs
> +    if "--compile-assets" in args do
I'm happy to report that my branch is merged and it's as 🚀 as I hoped, so we can go ahead and just always compile the assets for integration tests now.

2021-09-03 14:53 UTC, losvedir commented on README.md
> +  - `mix test.integration` or `mix test.integration --compile-assets` — run integration tests, optionally compiling frontend assets first.
No `--compile-assets` flag anymore.

2021-09-03 14:55 UTC, losvedir approved these changes
🎉

2021-09-03 19:44 UTC, merged